stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: zhangjiahao0401/maven
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: 制作镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: zhangjiahao0401/demo
      pushRemote: true
      registry: index.docker.io
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
