apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
  labels:
    app: demo
    dept: omgt
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      dept: omgt
      env: dev
  template:
    metadata:
      labels:
        app: demo
        dept: omgt
        env: dev
    spec:
      containers:
      - name: demo
        image: zhangjiahao0401/demo:latest
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
  labels:
    app: demo
    dept: omgt
    env: dev
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: demo
    dept: omgt
    env: dev
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
     app: demo
     dept: omgt
  name: demo-ingress
 
spec:
  rules:
  - host: demo-ingress.default.192.168.1.2.xip.io
    http:
      paths:
      - backend:
          serviceName: demo-service
          servicePort: 8080
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.2
